"""
Build data/adjectives.json with 1000+ categorized adjectives.

Run from project root: python scripts/build_adjectives.py
"""

from __future__ import annotations

import json
from pathlib import Path

CATEGORIES: dict[str, list[str]] = {
    "positive": [
        "fantastic", "amazing", "wonderful", "brilliant", "excellent", "outstanding",
        "superb", "magnificent", "splendid", "marvelous", "fabulous", "terrific",
        "incredible", "phenomenal", "extraordinary", "remarkable", "impressive",
        "stunning", "breathtaking", "dazzling", "glorious", "sublime", "divine",
        "perfect", "flawless", "impeccable", "exquisite", "elegant", "graceful",
        "charming", "delightful", "lovely", "beautiful", "gorgeous", "handsome",
        "pretty", "cute", "adorable", "sweet", "angelic", "heavenly", "radiant",
        "glowing", "luminous", "vibrant", "lively", "dynamic", "spirited", "zesty",
        "peppy", "bubbly", "perky", "upbeat", "optimistic", "hopeful", "inspiring",
        "motivating", "uplifting", "encouraging", "heartwarming", "touching",
        "moving", "powerful", "strong", "bold", "brave", "courageous", "fearless",
        "valiant", "heroic", "noble", "honorable", "worthy", "admirable", "respectable",
        "decent", "kind", "gentle", "caring", "compassionate", "loving", "warm",
        "friendly", "welcoming", "hospitable", "generous", "giving", "selfless",
        "helpful", "supportive", "loyal", "faithful", "devoted", "dedicated",
        "committed", "reliable", "trustworthy", "honest", "sincere", "genuine",
        "authentic", "real", "true", "pure", "innocent", "wholesome", "refreshing",
        "invigorating", "energizing", "thrilling", "exciting", "electrifying",
        "stimulating", "engaging", "captivating", "enchanting", "bewitching",
        "alluring", "attractive", "appealing", "desirable", "fetching", "winning",
        "triumphant", "victorious", "successful", "prosperous", "fortunate", "lucky",
        "blessed", "gifted", "talented", "skilled", "capable", "competent", "able",
        "adept", "proficient", "masterful", "expert", "genius", "clever", "smart",
        "wise", "sage", "insightful", "perceptive", "astute", "sharp", "keen",
        "quick", "agile", "nimble", "flexible", "adaptable", "resilient", "tough",
        "sturdy", "solid", "stable", "steady", "consistent", "dependable", "secure",
        "safe", "protected", "comfortable", "cozy", "snug", "relaxed", "easygoing",
        "laid-back", "chill", "mellow", "soothing", "calming", "tranquil", "serene",
        "peaceful", "quiet", "still", "harmonious", "balanced", "centered", "grounded",
        "mindful", "present", "aware", "conscious", "enlightened", "illuminated",
        "awakened", "evolved", "refined", "polished", "sophisticated", "classy",
        "chic", "stylish", "trendy", "modern", "fresh", "new", "novel", "original",
        "creative", "innovative", "inventive", "imaginative", "artistic", "expressive",
        "colorful", "vivid", "bright", "sunny", "cheerful", "joyful", "happy",
        "glad", "pleased", "content", "satisfied", "fulfilled", "complete", "whole",
        "unified", "connected", "bonded", "united", "together", "included", "accepted",
        "valued", "appreciated", "cherished", "treasured", "prized", "beloved", "adored",
        "worshipped", "revered", "esteemed", "honored", "celebrated", "acclaimed",
        "praised", "commended", "applauded", "admired", "loved", "liked", "favored",
    ],
    "negative": [
        "dull", "boring", "tedious", "monotonous", "lifeless", "flat", "stale",
        "drab", "gloomy", "grim", "bleak", "dismal", "depressing", "sad", "unhappy",
        "miserable", "wretched", "pitiful", "pathetic", "lame", "weak", "feeble",
        "frail", "fragile", "broken", "damaged", "hurt", "wounded", "bruised",
        "scarred", "tired", "exhausted", "weary", "drained", "spent", "burnt",
        "fried", "done", "over", "finished", "lost", "confused", "puzzled",
        "bewildered", "perplexed", "muddled", "foggy", "hazy", "cloudy", "murky",
        "dark", "shadowy", "sinister", "creepy", "spooky", "scary", "frightening",
        "terrifying", "horrifying", "awful", "terrible", "horrible", "dreadful",
        "atrocious", "abysmal", "appalling", "disgusting", "revolting", "nasty",
        "gross", "vile", "foul", "rotten", "spoiled", "sour", "bitter", "harsh",
        "rough", "coarse", "crude", "rude", "mean", "cruel", "harsh", "cold",
        "icy", "frozen", "numb", "detached", "distant", "aloof", "withdrawn",
        "shy", "timid", "nervous", "anxious", "worried", "stressed", "tense",
        "strained", "tight", "rigid", "stiff", "awkward", "clumsy", "goofy",
        "silly", "ridiculous", "absurd", "ludicrous", "preposterous", "outrageous",
        "wild", "unruly", "rowdy", "noisy", "loud", "obnoxious", "annoying",
        "irritating", "frustrating", "infuriating", "maddening", "aggravating",
        "stubborn", "obstinate", "pigheaded", "bullheaded", "hardheaded",
        "lazy", "sluggish", "slothful", "idle", "inactive", "passive", "apathetic",
        "indifferent", "uninterested", "bored", "unmotivated", "uninspired",
        "empty", "hollow", "vacant", "blank", "void", "lonely", "isolated",
        "abandoned", "forgotten", "ignored", "overlooked", "neglected", "rejected",
        "unwanted", "unloved", "hated", "despised", "loathed", "detested",
        "jealous", "envious", "bitter", "resentful", "spiteful", "vengeful",
        "angry", "furious", "irate", "livid", "enraged", "hostile", "aggressive",
        "violent", "destructive", "chaotic", "messy", "disorganized", "scattered",
        "frazzled", "disheveled", "unkempt", "sloppy", "careless", "reckless",
        "irresponsible", "immature", "childish", "petty", "shallow", "superficial",
        "fake", "phony", "false", "dishonest", "deceitful", "sneaky", "sly",
        "cunning", "manipulative", "controlling", "possessive", "clingy",
        "needy", "desperate", "hopeless", "helpless", "powerless", "defeated",
        "beaten", "crushed", "broken", "shattered", "devastated", "destroyed",
    ],
    "funny": [
        "hilarious", "comical", "witty", "humorous", "amusing", "entertaining",
        "playful", "mischievous", "naughty", "cheeky", "sassy", "spunky", "zany",
        "wacky", "goofy", "quirky", "eccentric", "oddball", "offbeat", "unconventional",
        "bizarre", "strange", "weird", "peculiar", "curious", "unusual", "unique",
        "random", "chaotic", "unpredictable", "spontaneous", "impulsive", "reckless",
        "bold", "daring", "adventurous", "fearless", "crazy", "insane", "mental",
        "bonkers", "nuts", "loony", "wacky", "kooky", "daffy", "dopey", "goofy",
        "silly", "dumb", "goofy", "clownish", "jester-like", "prankish", "joking",
        "teasing", "mocking", "sarcastic", "ironic", "deadpan", "dry", "droll",
        "absurd", "ridiculous", "ludicrous", "preposterous", "nonsensical",
        "waggish", "jocular", "facetious", "flippant", "tongue-in-cheek",
        "meme-worthy", "viral", "iconic", "legendary", "epic", "based", "cringe",
        "chaotic-good", "gremlin", "goblin", "feral", "unhinged", "delulu",
        "sus", "sussy", "skibidi", "rizzful", "unc", "goated", "mid", "bussin",
    ],
    "smart": [
        "intelligent", "brainy", "bright", "sharp", "clever", "witty", "astute",
        "brilliant", "genius", "gifted", "talented", "skilled", "knowledgeable",
        "learned", "educated", "informed", "aware", "insightful", "perceptive",
        "discerning", "judicious", "prudent", "wise", "sage", "philosophical",
        "thoughtful", "reflective", "contemplative", "analytical", "logical",
        "rational", "reasonable", "sensible", "practical", "pragmatic", "strategic",
        "tactical", "calculated", "methodical", "systematic", "organized", "structured",
        "efficient", "effective", "productive", "prolific", "industrious", "diligent",
        "studious", "scholarly", "academic", "intellectual", "cerebral", "mental",
        "cognitive", "conscious", "mindful", "aware", "alert", "attentive", "focused",
        "concentrated", "dedicated", "committed", "determined", "persistent",
        "tenacious", "resolute", "steadfast", "unwavering", "disciplined", "controlled",
        "composed", "collected", "poised", "articulate", "eloquent", "fluent",
        "expressive", "communicative", "persuasive", "convincing", "compelling",
        "influential", "impactful", "significant", "important", "notable", "noteworthy",
        "remarkable", "exceptional", "extraordinary", "rare", "precious", "invaluable",
    ],
    "emotional": [
        "emotional", "sensitive", "tender", "soft", "gentle", "delicate", "fragile",
        "vulnerable", "open", "raw", "honest", "transparent", "authentic", "real",
        "deep", "profound", "intense", "passionate", "fervent", "ardent", "zealous",
        "eager", "enthusiastic", "excited", "thrilled", "elated", "ecstatic", "euphoric",
        "blissful", "joyful", "happy", "cheerful", "gleeful", "jubilant", "merry",
        "festive", "celebratory", "grateful", "thankful", "appreciative", "humble",
        "modest", "shy", "bashful", "blushing", "flustered", "nervous", "anxious",
        "worried", "concerned", "caring", "empathetic", "sympathetic", "compassionate",
        "understanding", "patient", "forgiving", "accepting", "tolerant", "peaceful",
        "calm", "serene", "tranquil", "still", "quiet", "reflective", "melancholic",
        "nostalgic", "wistful", "longing", "yearning", "hopeful", "dreamy", "romantic",
        "sentimental", "touching", "moving", "poignant", "bittersweet", "complex",
        "layered", "nuanced", "subtle", "rich", "full", "whole", "complete",
    ],
    "romantic": [
        "romantic", "loving", "affectionate", "tender", "sweet", "caring", "devoted",
        "passionate", "ardent", "fervent", "desiring", "longing", "yearning", "dreamy",
        "enchanting", "captivating", "alluring", "seductive", "charming", "bewitching",
        "mesmerizing", "hypnotic", "magnetic", "attractive", "handsome", "beautiful",
        "gorgeous", "stunning", "radiant", "glowing", "luminous", "angelic", "divine",
        "heavenly", "ethereal", "fairylike", "magical", "mystical", "mysterious",
        "intriguing", "fascinating", "irresistible", "addictive", "intoxicating",
        "sensual", "sultry", "smoldering", "steamy", "warm", "cozy", "intimate",
        "private", "personal", "special", "unique", "precious", "treasured", "cherished",
        "beloved", "adored", "worshipped", "idolized", "admired", "revered", "esteemed",
        "honored", "valued", "appreciated", "desired", "wanted", "needed", "missed",
    ],
    "aesthetic": [
        "aesthetic", "artistic", "creative", "visual", "photogenic", "cinematic",
        "picturesque", "scenic", "beautiful", "lovely", "pretty", "cute", "adorable",
        "elegant", "graceful", "refined", "polished", "sleek", "smooth", "clean",
        "minimal", "simple", "pure", "crisp", "sharp", "vivid", "colorful", "vibrant",
        "pastel", "soft", "dreamy", "ethereal", "moody", "atmospheric", "dramatic",
        "bold", "striking", "eye-catching", "stunning", "breathtaking", "iconic",
        "timeless", "classic", "vintage", "retro", "modern", "futuristic", "edgy",
        "avant-garde", "experimental", "abstract", "surreal", "whimsical", "fantastical",
        "enchanted", "magical", "mystical", "celestial", "cosmic", "galactic", "stellar",
        "lunar", "solar", "golden", "silver", "crystal", "glittering", "shimmering",
        "sparkling", "glowing", "iridescent", "opalescent", "pearlescent", "velvet",
        "satin", "silky", "lush", "rich", "ornate", "decorative", "intricate", "detailed",
        "delicate", "fine", "subtle", "nuanced", "harmonious", "balanced", "symmetrical",
    ],
    "energetic": [
        "energetic", "dynamic", "active", "lively", "vibrant", "spirited", "animated",
        "peppy", "bouncy", "zippy", "snappy", "quick", "fast", "rapid", "swift",
        "agile", "nimble", "spry", "athletic", "sporty", "fit", "strong", "powerful",
        "mighty", "forceful", "intense", "fierce", "fiery", "blazing", "burning",
        "hot", "electric", "charged", "pumped", "hyped", "amped", "wired", "buzzing",
        "crackling", "sizzling", "explosive", "volcanic", "thunderous", "booming",
        "roaring", "raging", "wild", "untamed", "feral", "savage", "primal", "raw",
        "unstoppable", "unbreakable", "invincible", "legendary", "epic", "heroic",
        "champion", "winning", "dominant", "alpha", "boss", "chief", "leader",
        "commanding", "authoritative", "confident", "bold", "brave", "fearless",
        "daring", "adventurous", "exploratory", "pioneering", "trailblazing",
    ],
    "calm": [
        "calm", "peaceful", "serene", "tranquil", "quiet", "still", "gentle", "soft",
        "mellow", "relaxed", "easy", "chill", "laid-back", "cool", "composed", "collected",
        "poised", "centered", "grounded", "balanced", "stable", "steady", "even",
        "smooth", "fluid", "flowing", "graceful", "effortless", "natural", "organic",
        "earthy", "woodsy", "breezy", "airy", "light", "feathery", "cloudlike",
        "misty", "foggy", "hazy", "dreamy", "sleepy", "drowsy", "cozy", "snug",
        "warm", "comforting", "soothing", "healing", "restorative", "refreshing",
        "cooling", "shaded", "dusky", "twilight", "moonlit", "starlit", "silent",
        "hushed", "whispered", "subtle", "understated", "modest", "humble", "plain",
        "simple", "pure", "clear", "clean", "fresh", "crisp", "cool", "minty",
    ],
    "personality": [
        "confident", "bold", "brave", "fearless", "courageous", "strong", "resilient",
        "determined", "persistent", "ambitious", "driven", "motivated", "focused",
        "disciplined", "organized", "reliable", "loyal", "honest", "trustworthy",
        "kind", "generous", "humble", "modest", "patient", "calm", "wise", "mature",
        "responsible", "caring", "empathetic", "funny", "witty", "charming", "charismatic",
        "magnetic", "influential", "inspiring", "creative", "imaginative", "curious",
        "open-minded", "adaptable", "flexible", "easygoing", "friendly", "outgoing",
        "introverted", "thoughtful", "reflective", "passionate", "emotional", "sensitive",
        "quirky", "eccentric", "unique", "original", "authentic", "genuine", "real",
        "down-to-earth", "grounded", "practical", "logical", "analytical", "artistic",
        "expressive", "adventurous", "spontaneous", "playful", "mischievous", "rebellious",
        "independent", "free-spirited", "idealistic", "optimistic", "pessimistic",
        "realistic", "skeptical", "cynical", "sarcastic", "blunt", "direct", "honest",
        "diplomatic", "tactful", "polite", "respectful", "considerate", "thoughtful",
    ],
    "stylish": [
        "stylish", "fashionable", "trendy", "chic", "classy", "elegant", "sleek",
        "sharp", "dapper", "snazzy", "snappy", "flashy", "glamorous", "glitzy",
        "fabulous", "iconic", "legendary", "timeless", "classic", "vintage", "retro",
        "modern", "futuristic", "edgy", "bold", "daring", "avant-garde", "couture",
        "designer", "luxurious", "premium", "exclusive", "rare", "unique", "custom",
        "tailored", "fitted", "polished", "refined", "sophisticated", "urbane",
        "cosmopolitan", "worldly", "cultured", "artsy", "bohemian", "hipster",
        "streetwear", "sporty", "athleisure", "preppy", "grunge", "punk", "gothic",
        "minimalist", "maximalist", "eclectic", "layered", "coordinated", "matching",
        "accessorized", "detailed", "ornate", "decorative", "statement", "head-turning",
    ],
    "attitude": [
        "confident", "fearless", "bold", "fierce", "savage", "bossy", "dominant",
        "alpha", "commanding", "authoritative", "assertive", "decisive", "determined",
        "stubborn", "defiant", "rebellious", "independent", "free", "unbothered",
        "nonchalant", "cool", "chill", "unfazed", "calm", "collected", "poised",
        "classy", "sassy", "spicy", "fiery", "passionate", "intense", "dramatic",
        "extra", "over-the-top", "main-character", "protagonist", "iconic", "legendary",
        "unstoppable", "invincible", "untouchable", "elite", "premium", "luxury",
        "royal", "regal", "majestic", "noble", "grand", "epic", "heroic", "valiant",
        "brave", "courageous", "daring", "reckless", "wild", "chaotic", "unhinged",
        "mysterious", "enigmatic", "cryptic", "aloof", "distant", "cold", "icy",
        "warm", "friendly", "welcoming", "charming", "persuasive", "magnetic",
    ],
    "mood": [
        "happy", "sad", "angry", "excited", "bored", "tired", "sleepy", "hungry",
        "cozy", "stressed", "relaxed", "anxious", "calm", "peaceful", "chaotic",
        "messy", "organized", "focused", "distracted", "dreamy", "nostalgic",
        "hopeful", "hopeless", "inspired", "uninspired", "motivated", "lazy",
        "productive", "creative", "blank", "foggy", "clear", "bright", "dark",
        "moody", "emotional", "numb", "sensitive", "touchy", "grumpy", "cranky",
        "grouchy", "gloomy", "sunny", "stormy", "rainy", "windy", "breezy",
        "warm", "cold", "hot", "cool", "fresh", "stale", "new", "old", "young",
        "mature", "playful", "serious", "silly", "goofy", "witty", "sarcastic",
        "romantic", "lonely", "social", "antisocial", "outgoing", "shy", "bold",
        "timid", "brave", "scared", "fearless", "proud", "ashamed", "guilty",
        "innocent", "guilty", "jealous", "envious", "grateful", "bitter", "sweet",
    ],
}

# Additional bulk lists to exceed 1000 unique words
EXTRA_POSITIVE = [
    "ace", "aglow", "alive", "ample", "ardent", "avid", "beaming", "blissful",
    "bonny", "buoyant", "buoyed", "capable", "celestial", "choice", "civil",
    "class", "clean-cut", "clear-eyed", "comely", "convivial", "copacetic",
    "cordial", "cosy", "courtly", "crack", "crisp", "cushy", "dainty", "dandy",
    "dapper", "dauntless", "debonair", "decent", "decorous", "deluxe", "desired",
    "devout", "dexterous", "dignified", "dinkum", "distinct", "doughty", "dreamlike",
    "dulcet", "earnest", "ebullient", "ecstatic", "edifying", "effusive", "elated",
    "electric", "elevated", "elfin", "elite", "emerald", "eminent", "empyreal",
    "enamored", "endearing", "enduring", "energized", "engrossing", "enriched",
    "enthralling", "entrancing", "epic", "equable", "essential", "estimable",
    "ethereal", "euphoric", "evocative", "exalted", "exceeding", "excelling",
    "excelsior", "exemplary", "exhilarated", "exotic", "expansive", "expert",
    "exuberant", "exultant", "eye-popping", "fair", "faithful", "famed", "famous",
    "fancy", "fantabulous", "far-out", "fashioned", "fastidious", "faultless",
    "favorable", "fearless", "feisty", "felicitous", "fertile", "festal", "fiery",
    "fine", "finer", "finest", "firm", "fit", "fitting", "flamboyant", "flashy",
    "flawless", "fleet", "flourishing", "fluent", "flying", "foxy", "fragrant",
    "free", "frequent", "fresh-faced", "friendly", "frisky", "front", "fruitful",
    "fulgent", "full", "fun", "gallant", "game", "gamy", "garnished", "gay",
    "generous", "genial", "gentlemanly", "gilded", "glad", "glam", "gleaming",
    "glistening", "glittery", "global", "glossy", "glowing", "golden", "good",
    "goodly", "good-natured", "gorgeous", "graceful", "gracious", "grand",
    "grateful", "great", "greatest", "green", "groovy", "grounded", "growing",
    "grown", "guarded", "guided", "gutsy", "halcyon", "hale", "hallowed",
    "handsome", "handy", "happy-go-lucky", "hardy", "harmonic", "harmonious",
    "healthy", "heartfelt", "hearty", "heaven-sent", "helpful", "heralded",
    "heroic", "high", "high-class", "high-end", "high-minded", "high-spirited",
    "holy", "honest", "honored", "hopeful", "hospitable", "hot", "huggable",
    "humane", "humble", "humorous", "hunky", "hygienic", "ideal", "idyllic",
    "illustrious", "imaginative", "immaculate", "immense", "immortal", "immune",
    "impartial", "imperial", "important", "imposing", "improved", "incandescent",
    "included", "incomparable", "increasing", "incredible", "indelible",
    "independent", "indispensable", "individual", "indomitable", "industrious",
    "infallible", "infinite", "influential", "informative", "ingenious",
    "inimitable", "innocent", "innovative", "inquisitive", "insightful",
    "inspired", "inspiring", "instant", "instinctive", "integral", "integrated",
    "intelligent", "intense", "intent", "interested", "interesting", "internal",
    "intimate", "intrepid", "intriguing", "inventive", "invigorated", "inviting",
    "iridescent", "iron", "irreplaceable", "irresistible", "jazzy", "jolly",
    "jovial", "joyous", "jubilant", "judicious", "juicy", "just", "keen",
    "kinetic", "kingly", "kissable", "knightly", "knowing", "knowledgeable",
    "kosher", "lambent", "larger", "lasting", "latent", "laudable", "lavish",
    "lawful", "leading", "lean", "learned", "legal", "legendary", "legit",
    "legitimate", "lenient", "level", "liberal", "light", "lighthearted",
    "likable", "likely", "limber", "limitless", "lionhearted", "liquid",
    "literary", "lithe", "livable", "lively", "living", "logical", "luscious",
    "lush", "lustrous", "luxuriant", "luxurious", "lyrical", "magical",
    "magnetic", "magnificent", "main", "majestic", "major", "malleable",
    "manageable", "manly", "mannerly", "marked", "master", "matchless",
    "mature", "maximal", "meaningful", "measured", "meditative", "melodic",
    "memorable", "merciful", "merry", "meteoric", "methodical", "meticulous",
    "mighty", "mild", "mindful", "mint", "miraculous", "mirrored", "mobile",
    "model", "modern", "modest", "molded", "momentous", "monumental", "moral",
    "more", "motivated", "moving", "much", "muscular", "musical", "must",
    "mutual", "mysterious", "mystic", "mythic", "naive", "native", "natural",
    "navigable", "near", "neat", "necessary", "needed", "neighborly", "neon",
    "nestled", "new", "nice", "nifty", "nimble", "noble", "noiseless", "nominal",
    "normal", "notable", "noted", "novel", "nuclear", "numinous", "nutritious",
    "obedient", "objective", "obliging", "observant", "obtainable", "obvious",
    "occasional", "oceanic", "odd", "official", "okay", "omniscient", "one",
    "open", "operable", "optimal", "optimistic", "opulent", "oral", "orange",
    "orbital", "orderly", "organic", "oriented", "original", "ornate", "orthodox",
    "other", "outgoing", "outlandish", "outrageous", "outside", "outstanding",
    "oval", "over", "overall", "overjoyed", "overnight", "overt", "pacific",
    "palatial", "pale", "palpable", "pampered", "panoramic", "parallel",
    "paramount", "parental", "park", "partial", "particular", "passionate",
    "passive", "past", "pastel", "patent", "patient", "patriotic", "peaceable",
    "peaceful", "peachy", "peaked", "pearl", "peculiar", "pedigreed", "peerless",
    "penetrating", "pensive", "peppy", "perceptive", "perfect", "perfumed",
    "periodic", "perky", "permanent", "permissive", "personal", "persuasive",
    "pert", "pertinent", "petite", "petty", "phantom", "phenomenal", "philosophic",
    "phoenix", "physical", "picturesque", "pilot", "pious", "piquant", "pithy",
    "pivotal", "placid", "plaid", "plain", "plaintive", "planar", "plastic",
    "platinum", "plausible", "playful", "pleasant", "pleased", "pleasing",
    "plenary", "plentiful", "pliable", "plucky", "plump", "plush", "poetic",
    "poignant", "pointed", "poised", "polished", "polite", "political", "popular",
    "porous", "portable", "portly", "positive", "possible", "postal", "potent",
    "potential", "powerful", "practical", "pragmatic", "praiseworthy", "precious",
    "precise", "predominant", "preeminent", "preferred", "premium", "prepared",
    "present", "presidential", "pretty", "previous", "priceless", "primal",
    "primary", "prime", "princely", "principal", "pristine", "private", "prize",
    "pro", "proactive", "probable", "productive", "professional", "proficient",
    "profound", "progressive", "prolific", "prominent", "promising", "proper",
    "prophetic", "prosperous", "protective", "proud", "proven", "prudent",
    "punctual", "pure", "purple", "purposeful", "quaint", "qualified", "quality",
    "quantum", "quarterly", "queenly", "quick", "quiet", "quintessential", "quirky",
    "quixotic", "radiant", "rapid", "rare", "rational", "ravishing", "raw",
    "ready", "real", "realistic", "reasonable", "reassuring", "rebel", "recent",
    "receptive", "recognized", "recommended", "record", "recovered", "red",
    "refined", "reflective", "refreshing", "regal", "regular", "reigning",
    "related", "relative", "relaxed", "relevant", "reliable", "relieved",
    "remarkable", "renewed", "renowned", "reputable", "respected", "restful",
    "restored", "restrained", "retained", "retired", "retro", "revealing",
    "revered", "revived", "rewarding", "rich", "right", "righteous", "ringed",
    "ripe", "rising", "ritzy", "robust", "rocking", "rolling", "romantic",
    "roomy", "rooted", "rosy", "rotating", "rough", "round", "rousing", "royal",
    "rubbery", "ruby", "rugged", "ruled", "rumbling", "running", "rural", "rustic",
    "sacred", "safe", "sage", "saintly", "salient", "salty", "salubrious",
    "sandy", "sane", "sapient", "sassy", "satin", "satisfied", "saucy", "saving",
    "savvy", "scenic", "scholarly", "scientific", "scintillating", "sensible",
    "sensitive", "seraphic", "serene", "set", "settled", "severe", "shapely",
    "sharp", "sheer", "shining", "shiny", "shocking", "shore", "short", "showy",
    "shrewd", "shy", "significant", "silent", "silken", "silky", "silver",
    "similar", "simple", "sincere", "singular", "sinless", "sizable", "skilled",
    "skim", "sky", "slate", "sleek", "sleepy", "slender", "slight", "slim",
    "slippery", "slow", "slushy", "small", "smart", "smashing", "smiling",
    "smitten", "smooth", "snappy", "snazzy", "snowy", "snug", "soaring", "social",
    "soft", "solar", "solid", "solo", "solvable", "sonorous", "soothing", "sophisticated",
    "sought", "sound", "southern", "spacious", "spare", "sparkling", "sparse",
    "spatial", "special", "specific", "spectacular", "speedy", "spellbinding",
    "spicy", "spiffy", "spirited", "spiritual", "splendid", "spontaneous", "sporty",
    "spotless", "spotlit", "sprightly", "springy", "spry", "square", "stable",
    "stacked", "stainless", "stately", "static", "statuesque", "staunch",
    "steadfast", "steady", "steamy", "steel", "stellar", "sterling", "sticky",
    "stiff", "still", "stimulating", "stingy", "stirring", "stocky", "stoic",
    "stoked", "stolid", "stoned", "stony", "stormy", "stout", "straight",
    "straightforward", "strange", "strategic", "streamlined", "street", "strength",
    "strenuous", "strict", "striking", "strong", "structural", "stubborn",
    "studious", "stunning", "sturdy", "stylish", "suave", "sublime", "substantial",
    "subtle", "successful", "succinct", "sudden", "sufficient", "sugary", "suitable",
    "sultry", "summery", "sunny", "super", "superb", "superior", "supple",
    "supreme", "sure", "surface", "surging", "surprising", "surrounding", "surviving",
    "suspect", "sustainable", "swank", "swanky", "sweet", "swell", "swift",
    "swimming", "swinging", "sylvan", "symmetric", "sympathetic", "synthetic",
    "systematic", "tactful", "talented", "talkative", "tall", "tame", "tangible",
    "tart", "tasteful", "tasty", "taught", "taut", "teachable", "teal", "telling",
    "temperate", "temporal", "tempting", "tenacious", "tender", "tense", "terminal",
    "terrific", "terse", "tested", "thankful", "theatrical", "thematic", "theoretical",
    "thick", "thin", "thinkable", "third", "thorough", "thoughtful", "thrifty",
    "thrilling", "thriving", "tidy", "tight", "timeless", "timely", "timid",
    "tingling", "tinkling", "tinted", "tiny", "tired", "titanic", "toasty",
    "tolerant", "tonal", "top", "topical", "topless", "topnotch", "torrid",
    "total", "touching", "tough", "towering", "toxic", "traditional", "trained",
    "tranquil", "transcendent", "transparent", "transient", "transitional",
    "translucent", "transmitted", "traveled", "treasured", "treated", "tremendous",
    "trendy", "tribal", "tricky", "trim", "triple", "triumphant", "trivial",
    "tropical", "true", "trusted", "trusty", "truthful", "tubular", "tuned",
    "turbulent", "turgid", "twin", "twinkling", "twisted", "typical", "ultimate",
    "ultra", "umpire", "unafraid", "unbiased", "unbound", "unbroken", "uncanny",
    "uncommon", "undaunted", "under", "understood", "undying", "unearthly",
    "unfailing", "unforgettable", "unified", "unique", "united", "universal",
    "unkempt", "unknown", "unlimited", "unlocked", "unnamed", "unreal", "unrivaled",
    "unruffled", "unseen", "unselfish", "unsettled", "unsung", "untamed",
    "untapped", "unusual", "unwavering", "upbeat", "upcoming", "updated", "upfront",
    "uphill", "uplifted", "upper", "upright", "uprising", "upscale", "upstairs",
    "uptight", "uptown", "upward", "urban", "urgent", "usable", "used", "useful",
    "usual", "utmost", "utopian", "utter", "vacant", "vague", "valid", "valiant",
    "valuable", "valued", "vanilla", "vapid", "variable", "varied", "vast",
    "vaulted", "vegan", "vehement", "velvet", "venerable", "venial", "venturesome",
    "verbal", "verdant", "verified", "veritable", "versatile", "vertical", "very",
    "vested", "veteran", "viable", "vibrant", "vicarious", "victorious", "vigilant",
    "vigorous", "vile", "vintage", "violent", "violet", "virile", "virtual",
    "virtuous", "visible", "visionary", "visiting", "visual", "vital", "vivid",
    "vocal", "vocational", "voiced", "volatile", "volcanic", "voluntary", "voracious",
    "voting", "vowed", "vulnerable", "wacky", "wan", "wanted", "warlike", "warm",
    "warmhearted", "warning", "wary", "washed", "waste", "watchful", "watery",
    "waving", "waxen", "wayward", "wealthy", "wearable", "weathered", "webbed",
    "wedded", "weekly", "weepy", "weighty", "welcome", "well", "western", "wet",
    "whimsical", "whirling", "whispered", "white", "whole", "wholesome", "wicked",
    "wide", "wieldy", "wild", "willful", "willing", "wily", "windy", "winged",
    "winning", "wintery", "wired", "wise", "wishful", "wistful", "witchy",
    "withdrawn", "witty", "wizard", "wobbly", "woeful", "womanly", "wonder",
    "wondrous", "wooden", "woodsy", "woody", "wordy", "workable", "working",
    "worldly", "worldwide", "wormy", "worried", "worse", "worst", "worth",
    "worthwhile", "worthy", "wounded", "woven", "wrapped", "wrecked", "writhing",
    "written", "wrong", "wry", "yawning", "yearly", "yearning", "yellow", "yielding",
    "young", "youthful", "yummy", "zany", "zealous", "zen", "zero", "zesty",
    "zigzag", "zippy", "zonal", "zoned", "zonked", "zoological", "zesty",
]


def build() -> dict:
    """Merge categories and extras into unique sorted list."""
    seen: set[str] = set()
    all_words: list[str] = []

    for category, words in CATEGORIES.items():
        for w in words:
            key = w.strip().lower()
            if key and key not in seen:
                seen.add(key)
                all_words.append(key)

    for w in EXTRA_POSITIVE:
        key = w.strip().lower()
        if key and key not in seen:
            seen.add(key)
            all_words.append(key)

    all_words.sort()
    return {
        "meta": {
            "total": len(all_words),
            "version": "1.0",
            "description": "WhatsApp Identity Agent adjective dataset",
        },
        "categories": {k: sorted(set(v)) for k, v in CATEGORIES.items()},
        "adjectives": all_words,
    }


def main() -> None:
    base = Path(__file__).resolve().parent.parent
    out = base / "data" / "adjectives.json"
    data = build()
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Wrote {data['meta']['total']} adjectives to {out}")


if __name__ == "__main__":
    main()
